name = "neutron-ftw"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "neutron-ftw_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "neutron-ftw.wasm"
command = "npm run build:release"
